server:
  port: 9090

spring:
  message:
    encoding:UTF-8
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    charset: UTF-8
    suffix: .html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/privatebox
      username: root
      password: hyiechyiec
  jpa:
    database: MYSQL
    #naming:
      #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true